[package]
name = "hello_package"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name="help"
path="src/bin/help.rs"

[[bin]]
name="now"
path="src/bin/now.rs"